import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeProvider";
import { ToastContainer } from "@/components/ToastContainer";




export const metadata: Metadata = {
  title: "GeoLib",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      >
        <ToastContainer />
        <ThemeProvider>
        {children}

        </ThemeProvider>
      </body>
    </html>
  );
}
